### PR TITLE
fail tests on oc build failure

### PR DESCRIPTION
**Pull request by wenzowski**
an isolated test for #5

### CODE REVIEW

**Comment by wenzowski** [comment]
@iynere is there a CLA or something I need to complete that's blocking this test run?

**Comment by iynere** [comment]
@wenzowski i don't believe this repo is set to build forked PRs on circle, and even if it was, our integration testing depends on access to some secrets that we wouldn't want to pass to forked PRs

our typical approach here is to merge community contributions into a `staging` branch so that tests can run—@lokst does that sound good to you ?

**Comment by lokst** [comment]
@iynere @wenzowski I wasn't sure if there are limitations of the local cluster that would make it difficult for this test to pass so I pushed the changes to a different branch to get the tests to run on CircleCI.
I haven't been able to get`oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git` to work in the local cluster yet as I haven't figured out how to make the image get pushed to a different url from `https://172.30.1.1:5000/v2/`  But if we rework this test to use `docker push` (the approach in https://github.com/CircleCI-Public/redhat-openshift-orb/issues/5#issuecomment-510735732) I believe the test can pass.

**Comment by wenzowski** [comment]
@lokst would you mind doing the temporary branch dance? This now passing on my fork

**Comment by lokst** [comment]
@wenzowski Your changes are now in the 0.2.0 version of the orb! 🎉

**Pull request merged**
